#!/usr/bin/env bash
# vim: set ft=sh :

# BSD 3-Clause License
#
# Copyright (c) 2020-2022, Chris 'sh0shin' Frage
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the copyright holder nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -o pipefail -eu

readonly DH_SELF_FILE="${BASH_SOURCE[0]}"
readonly DH_SELF_NAME="${DH_SELF_FILE##*/}"
readonly DH_SELF_PATH="${DH_SELF_FILE%/*}"
readonly DH_SELF_VERSION="v0.3.0"
readonly DH_SELF_URL="https://sh0shin.org/dothier"

# <level> <message>
__dothier_msg() {
  local DH_LEVEL="$1"
  shift
  local -a DH_MSG=( "$@" )

  local _MSG="${DH_MSG[*]}"
  local _NAME

  _NAME="${FUNCNAME[1]#__dothier_*}"
  _NAME="${_NAME//__dothier/dothier}"

  local _COLOR=""
  local _NOCOLOR=""

  if [[ "$DOTHIER_SHORTMSG" == true ]]
  then
    _MSG="${_MSG//${HOME}/\~}"
  fi

  if [[ "$DOTHIER_COLOR" == true ]]
  then
    case "$DH_LEVEL"
    in
      e|error)
        _COLOR="\033[1;31m"
      ;;
      w|warning)
        _COLOR="\033[0;33m"
      ;;
      n|notice)
        if [[ $DOTHIER_QUIET == true ]]
        then
          return
        fi
        _COLOR="\033[0;37m"
      ;;
      i|info)
        if [[ $DOTHIER_QUIET == true ]]
        then
          return
        fi
        _COLOR="\033[0;36m"
      ;;
      v|verbose)
        if [[ $DOTHIER_QUIET == true ]] || [[ $DOTHIER_VERBOSE == false ]]
        then
          return
        fi
        _COLOR="\033[0;36m"
      ;;
      *)
        _COLOR="\033[0;34m"
      ;;
    esac
    _NOCOLOR="\033[0m"
  fi

  echo -e "${_COLOR}${_NAME}\t${_MSG}${_NOCOLOR}"
  return
} #__dothier_msg

__dothier_usage() {
  echo "$DH_SELF_NAME $DH_SELF_VERSION ($DH_SELF_URL)"
} #__dothier_usage

__dothier_help() {
  __dothier_usage

  echo "Options:"
  echo
  echo " -C       : Disable colorized messages"
  echo " -D depth : Set git clone depth (default: $DOTHIER_GIT_DEPTH)"
  echo " -G       : Enable git pull (default: $DOTHIER_GIT_PULL)"
  echo " -H home  : Home directory (default: $DOTHIER_HOME)"
  echo " -K file  : Use git-crypt key file"
  echo " -R       : Enable remove/delete mode (default: $DOTHIER_REMOVE)"
  echo " -S       : Enable short message mode (default: $DOTHIER_SHORTMSG)"
  echo " -T       : Enable tmutil exclude (macOS only default: $DOTHIER_TMUTIL)"
  echo " -U       : Set umask (default: $DOTHIER_UMASK)"

  echo " -d dir   : Dotfiles root directory for recursive mode (default: $DOTHIER_DOTROOT)"
  echo " -f file  : Dothier file (default: $DOTHIER_FILE)"
  echo " -h       : Show this help"
  echo " -n       : Enable dry-run mode (default: $DOTHIER_DRYRUN)"
  echo " -q       : Enable quiet mode (default: $DOTHIER_QUIET)"
  echo " -r       : Enable recursive mode (see: -d default: $DOTHIER_RECURSIVE)"
  echo " -v       : Be verbose (default: $DOTHIER_VERBOSE)"

} #__dothier_help

__dothier_stat() {
  local DH_PATH="$1"
  local DH_STAT

  if [[ -e "$DH_PATH" ]]
  then
    case "$OSTYPE"
    in
      darwin*|freebsd*|openbsd*)
        DH_STAT="$( stat -f "%Mp%Lp" "$DH_PATH" )"
      ;;
      linux*)
        DH_STAT="$( stat -c "%#a" "$DH_PATH" )"
      ;;
    esac
    echo "${DH_STAT:(-4)}"
  fi
} #__dothier_stat


# <url> <dst> <mode>
__dothier_git() {
  local DH_URL="$1"
  local DH_DST="$2"
  local DH_MODE="$3"

  if [[ ! -d "$DH_DST" ]]
  then
    __dothier_msg i "clone: $DH_URL $DH_DST"
    $DH_RUN git clone --depth "$DOTHIER_GIT_DEPTH" "$DH_URL" "$DH_DST"
    __dothier_mode "$DH_DST" "$DH_MODE"
  else
    if [[ "$DOTHIER_GIT_PULL" == true ]]
    then
      __dothier_msg i "pull: $DH_DST"
      $DH_RUN git -C "$DH_DST" pull
    else
      __dothier_msg v "no pull: $DH_DST"
    fi

    __dothier_mode "$DH_DST" "$DH_MODE"
  fi
} #__dothier_git

# <repo> <file>
declare DH_CRYPT_REPO=""
__dothier_crypt() {
  local DH_REPO="$1"
  local DH_FILE="$2"
  local -a _GREP

  if [[ "$DH_REPO" == "$DH_CRYPT_REPO" ]]
  then
    __dothier_msg v "unlocked: $DH_REPO"
    return
  fi

  if [[ -n "$DOTHIER_GIT_KEY" ]]
  then
    if [[ -e "$DOTHIER_GIT_KEY" ]]
    then

      if [[ "$OSTYPE" =~ (darwin|freebsd) ]]
      then
        _GREP=( "-rq" )
      elif [[ "$OSTYPE" =~ linux ]]
      then
        _GREP=( "-qrsPa" )
      fi

      if grep "${_GREP[@]}" "\x00GITCRYPT" "$DH_FILE"
      then
        __dothier_msg i "unlock: $DH_REPO"
        $DH_RUN git -C "$DH_REPO" crypt unlock "$DOTHIER_GIT_KEY"
        DH_CRYPT_REPO="$DH_REPO"
      fi
    fi
  fi
} #__dothier_crypt

# <path> <mode>
__dothier_mode() {
  local DH_PATH="$1"
  local DH_MODE="$2"
  local _MODE

  if [[ "$DH_MODE" == "0000" ]]
  then
    if [[ -L "$DH_PATH" ]]
    then
      __dothier_msg i "rmlink: $DH_PATH"
      $DH_RUNRM rm "$DH_PATH"
    elif [[ -d "$DH_PATH" ]]
    then
      __dothier_msg i "rmdir: $DH_PATH"
      $DH_RUNRM rmdir "$DH_PATH"
    elif [[ -f "$DH_PATH" ]]
    then
      __dothier_msg i "rmfile: $DH_PATH"
      $DH_RUNRM rm "$DH_PATH"
    fi
  else
    _MODE="$( __dothier_stat "$DH_PATH" )"

    if [[ -n "$_MODE" ]] && [[ "$_MODE" != "$DH_MODE" ]] && [[ ! -L "$DH_PATH" ]]
    then
      __dothier_msg i "chmod: $DH_MODE $DH_PATH ($_MODE)"
      $DH_RUN chmod "$DH_MODE" "$DH_PATH"
    else
      __dothier_msg v "ok: $DH_PATH ($DH_MODE)"
    fi
  fi
} #__dothier_mode

# <src> <dst> <mode> <link>
__dothier_dir() {
  local DH_SRC="$1"
  local DH_DST="$2"
  local DH_MODE="$3"
  local DH_LINK="$4"

  if [[ ! -d "$DH_DST" ]] && [[ ! "$DH_LINK" =~ (yes|true) ]]
  then
    if [[ "$DH_MODE" != "0000" ]]
    then
      __dothier_msg i "mkdir: $DH_DST"
      $DH_RUN mkdir -m "$DH_MODE" "$DH_DST"
    else
      __dothier_mode "$DH_DST" "$DH_MODE"
    fi
  elif [[ "$DH_LINK" =~ (yes|true) ]]
  then
    __dothier_link "$DH_SRC" "$DH_DST" "$DH_MODE"
  else
    __dothier_msg v "ok: $DH_DST"
    __dothier_mode "$DH_DST" "$DH_MODE"
  fi
} # __dothier_dir

# <src> <dst> <mode>
__dothier_link() {
  local _SRC="$1"
  local _DST="$2"
  local _MODE="$3"
  local _LINK

  # absolute
  if [[ "$_SRC" =~ \~ ]]
  then
    _SRC="${_SRC//\~/$HOME}"
  fi

  if [[ -L "$_DST" ]] && [[ "$_MODE" == "0000" ]]
  then
    __dothier_mode "$_DST" "$_MODE"

  elif [[ -L "$_DST" ]]
  then
    _LINK=$( readlink "$_DST" )

    if [[ "$_LINK" != "$_SRC" ]]
    then
      __dothier_msg w "rmlink: wrong $_LINK ($_SRC)"
      $DH_RUNRM rm "$_DST"
      __dothier_msg i "link: $_SRC $_DST"
      $DH_RUNRM ln -s "$_SRC" "$_DST"
      __dothier_mode "$_SRC" "$_MODE"
    else
      __dothier_msg v "ok: $_DST"
      __dothier_mode "$_SRC" "$_MODE"
    fi

  elif [[ ! -L "$_DST" ]] && [[ "$_MODE" != "0000" ]]
  then
    if [[ -e "$_SRC" ]]
    then
      __dothier_msg i "link: $_SRC $_DST"
      $DH_RUN ln -s "$_SRC" "$_DST"
      __dothier_mode "$_SRC" "$_MODE"
    else
      __dothier_msg e "not found: $_SRC"
    fi
  fi
} #__dothier_link

# <path> <tmex>
__dothier_tmutil() {
  local DH_PATH="$1"
  local DH_TMEX="$2"

  if [[ ! "$OSTYPE" =~ darwin ]]
  then
    return
  fi

  if [[ -d "$DH_PATH" ]] && [[ ! -L "$DH_PATH" ]]
  then
    if ( xattr "$DH_PATH" | grep -q com_apple_backup_excludeItem )
    then

      if [[ "$DH_TMEX" == false ]]
      then
        __dothier_msg i "remove exclusion: $DH_PATH"
        $DH_RUN tmutil removeexclusion "$DH_PATH"
      else
        __dothier_msg v "ok: $DH_PATH"
      fi

    elif [[ "$DH_TMEX" == true ]]
    then
      __dothier_msg i "add exclusion: $DH_PATH"
      $DH_RUN tmutil addexclusion "$DH_PATH"
    else
      __dothier_msg v "ok: $DH_PATH"
    fi
  fi
} #__dothier_tmutil

__dothier_proc() {
  local DH_TYPE="$1"
  shift
  local DH_REPO="$1"
  shift
  local -a DH_PROC=( "$@" )

  for _PROC in "${DH_PROC[@]}"
  do
    read -r _PATH _MODE _LINK _TMEX <<< "$_PROC"

    # rgit|git
    if [[ "$DH_TYPE" =~ ^(rgit|git)$ ]]
    then
      if [[ "$DH_TYPE" == "rgit" ]]
      then
        # default destination from url
        if [[ "$_LINK" =~ (no|false) ]]
        then
          _DST="${DH_REPO}/${_PATH##*/}"
          _DST="${_DST//.git}"
        else
          _DST="${DH_REPO}/${_LINK}"
        fi
      fi

      if [[ "$DH_TYPE" == "git" ]]
      then
        # default destination from url
        if [[ "$_LINK" =~ (no|false) ]]
        then
          _DST="${DOTHIER_HOME}/${_PATH##*/}"
          _DST="${_DST//.git}"
        else
          _DST="${DOTHIER_HOME}/${_LINK}"
        fi
      fi

      __dothier_git "$_PATH" "$_DST" "$_MODE"
    fi

    # rdir
    if [[ "$DH_TYPE" == "rdir" ]]
    then
      _DST="${DH_REPO}/${_PATH}"
      _SRC="$_DST"

      if [[ -d "$_DST" ]]
      then
        __dothier_mode "$_DST" "$_MODE"
      fi
    fi

    # dir
    if [[ "$DH_TYPE" == "dir" ]]
    then
      _DST="${DOTHIER_HOME}/${_PATH}"
      _SRC="${DH_REPO}/${_PATH}"

      __dothier_dir "$_SRC" "$_DST" "$_MODE" "$_LINK"

      if [[ "$_MODE" != "0000" ]]
      then
        __dothier_mode "$_SRC" "$_MODE"
      fi
    fi

    # rfile
    if [[ "$DH_TYPE" == "rfile" ]]
    then
      _DST="${DH_REPO}/${_PATH}"
      _SRC="$_DST"
      __dothier_mode "$_DST" "$_MODE"
    fi

    # file
    if [[ "$DH_TYPE" == "file" ]]
    then
      _DST="${DOTHIER_HOME}/${_PATH}"
      _SRC="${DH_REPO}/${_PATH}"

      __dothier_crypt "$DH_REPO" "$_SRC"

      if [[ "$_LINK" =~ (yes|true) ]]
      then
        __dothier_link "$_SRC" "$_DST" "$_MODE"
      else
        __dothier_mode "$_SRC" "$_MODE"
      fi
    fi

    # link
    if [[ "$DH_TYPE" == "link" ]]
    then
      _DST="${DOTHIER_HOME}/${_PATH}"
      _SRC="${_LINK}"
      __dothier_link "$_SRC" "$_DST" "$_MODE"
    fi

    if [[ "$DOTHIER_TMUTIL" == true ]] && [[ "$_MODE" != "0000" ]]
    then
      __dothier_tmutil "$_DST" "$_TMEX"
    fi

  done
} #__dothier_proc

__dothier_read() {
  local DH_READ="${1:-"$DOTHIER_FILE"}"
  local DH_REPO

  local -a DH_RDIR
  local -a DH_RFILE
  local -a DH_RGIT

  local -a DH_DIR
  local -a DH_FILE
  local -a DH_GIT
  local -a DH_LINK

  if [[ -z "$DH_READ" ]]
  then
    __dothier_msg e "no $DOTHIER_FILE file!"
    return 1
  fi

  if [[ ! -e "$DH_READ" ]]
  then
    __dothier_msg e "not found: $DH_READ"
    return 1
  fi

  if [[ ! -d "${DH_READ%/*}" ]]
  then
    DH_REPO="$PWD"
  else
    DH_REPO="$( cd "${DH_READ%/*}" && echo "$PWD" )"
  fi

  __dothier_msg v "repo: $DH_REPO"
  __dothier_msg n "hier: $DH_READ"

  local -a _CONT
  local _READ

  local _PATH
  local _TYPE
  local _MODE
  local _LINK
  local _TMEX
  local _MISC

  mapfile -t -n 0 _CONT < <( grep -E "^[^#]" "$DH_READ" )

  for _READ in "${_CONT[@]}"
  do
    IFS=$'\t ' read -r _PATH _TYPE _MODE _LINK _MISC <<< "$_READ"

    # default mode
    local __MODE
    case "$_TYPE"
    in
      rdir|dir|rgit|git)
        __MODE="$DH_DMODE"
      ;;
      rfile|file)
        __MODE="$DH_FMODE"
      ;;
      link)
        __MODE="inherit"
      ;;
    esac

    # swap empty mode
    if [[ ! "$_MODE" =~ ^(@)?[0-9]+$ ]]
    then
      if [[ "$_MODE" =~ ^(yes|no|true|false)$ ]] || [[ "$_MODE" =~ ^(.*)$ ]]
      then
        _LINK="$_MODE"
        _MODE="$__MODE"
      fi
    fi
    unset __MODE

    # tmutil exclude
    if [[ "$_MODE" =~ ^@ ]]
    then
      _TMEX=true
      _MODE="${_MODE##@}"
    else
      _TMEX=false
    fi

    # default link
    : "${_LINK:="no"}"
    : "${_MISC:=""}"

    case "$_TYPE"
    in
      rdir)
        DH_RDIR+=( "$_PATH $_MODE no $_TMEX" )
      ;;
      rfile)
        DH_RFILE+=( "$_PATH $_MODE no $_TMEX" )
      ;;
      rgit)
        DH_RGIT+=( "$_PATH $_MODE $_LINK $_TMEX" )
      ;;
      dir)
        DH_DIR+=( "$_PATH $_MODE $_LINK $_TMEX" )
      ;;
      file)
        DH_FILE+=( "$_PATH $_MODE $_LINK $_TMEX" )
      ;;
      git)
        DH_GIT+=( "$_PATH $_MODE $_LINK $_TMEX" )
      ;;
      link)
        DH_LINK+=( "$_PATH $_MODE $_LINK $_TMEX" )
      ;;
    esac
  done

  # proc
  ## rgit
  __dothier_proc rgit "$DH_REPO" "${DH_RGIT[@]}"
  ## rdir
  __dothier_proc rdir "$DH_REPO" "${DH_RDIR[@]}"
  ## rfile
  __dothier_proc rfile "$DH_REPO" "${DH_RFILE[@]}"

  ## git
  __dothier_proc git "$DH_REPO" "${DH_GIT[@]}"
  ## dir
  __dothier_proc dir "$DH_REPO" "${DH_DIR[@]}"
  ## file
  __dothier_proc file "$DH_REPO" "${DH_FILE[@]}"
  ## link
  __dothier_proc link "$DH_REPO" "${DH_LINK[@]}"

  return
} #__dothier_read

# -C
declare DOTHIER_COLOR="${DOTHIER_COLOR:-true}"
# -G
declare DOTHIER_GIT_PULL="${DOTHIER_GIT_PULL:-false}"
declare DOTHIER_GIT_DEPTH="${DOTHIER_GIT_DEPTH:-1}"
# -H
declare DOTHIER_HOME="${DOTHIER_HOME:-"$HOME"}"
# -K
declare DOTHIER_GIT_KEY="${DOTHIER_GIT_KEY:-""}"
# -R
declare DOTHIER_REMOVE="${DOTHIER_REMOVE:-false}"
declare DH_RUNRM="echo -e \t(no-remove): "
# -S
declare DOTHIER_SHORTMSG="${DOTHIER_SHORTMSG:-false}"
# -T
declare DOTHIER_TMUTIL="${DOTHIER_TMUTIL:-false}"

# -c
declare DOTHIER_CONFIG="${DOTHIER_CONFIG:-"${HOME}/.config/dothier"}"
# -d
declare DOTHIER_DOTROOT="${DOTHIER_DOTROOT:-"${DOTHIER_HOME}/.dotfiles"}"

# -f
declare DOTHIER_FILE="${DOTHIER_FILE:-".hier"}"

declare DOTHIER_UMASK="${DOTHIER_UMASK:-"$( umask )"}"
declare DH_DMODE="0755"
declare DH_FMODE="0644"

# -n
declare DOTHIER_DRYRUN="${DOTHIER_DRYRUN:-false}"
declare DH_RUN="command"

# -q
declare DOTHIER_QUIET="${DOTHIER_QUIET:-false}"
# -r
declare DOTHIER_RECURSIVE="${DOTHIER_RECURSIVE:-false}"
# -v
declare DOTHIER_VERBOSE="${DOTHIER_VERBOSE:-false}"

__dothier() {
  # config
  if [[ -e "$DOTHIER_CONFIG" ]]
  then
    __dothier_msg n "config: $DOTHIER_CONFIG"
    # shellcheck disable=SC1090
    source "$DOTHIER_CONFIG"
  fi

  while getopts ":CD:GH:K:RSTU:c:d:f:hnqrv" OPT
  do
    case "$OPT"
    in
      C)
        DOTHIER_COLOR=false
      ;;
      D)
        DOTHIER_GIT_DEPTH="$OPTARG"
      ;;
      G)
        DOTHIER_GIT_PULL=true
      ;;
      H)
        DOTHIER_HOME="$OPTARG"
      ;;
      K)
        DOTHIER_GIT_KEY="$OPTARG"
      ;;
      R)
        DOTHIER_REMOVE=true
        DH_RUNRM="command"
      ;;
      S)
        DOTHIER_SHORTMSG=true
      ;;
      T)
        DOTHIER_TMUTIL=true
      ;;
      U)
        DOTHIER_UMASK="$OPTARG"
      ;;
      c)
        DOTHIER_CONFIG="$OPTARG"
      ;;
      d)
        DOTHIER_DOTROOT="$OPTARG"
      ;;
      h)
        __dothier_help
        exit 0
      ;;
      n)
        DOTHIER_DRYRUN=true
        DH_RUN="echo -e \t(dry-run): "
      ;;
      q)
        DOTHIER_QUIET=true
      ;;
      r)
        DOTHIER_RECURSIVE=true
      ;;
      v)
        DOTHIER_VERBOSE=true
      ;;
      :)
        __dothier_msg e "option: -${OPTARG} required argument missing!"
        exit 1
      ;;
      ?)
        __dothier_msg e "option: -${OPTARG} is unknown!"
        exit 1
      ;;
    esac
  done

  # umask
  umask "$DOTHIER_UMASK"

  DH_DMODE="$( printf '%#o' $(( 0777 & ~DOTHIER_UMASK )) )"
  DH_FMODE="$( printf '%#o' $(( 0777 & ~0111 & ~DOTHIER_UMASK )) )"

  if [[ ! -d "$DOTHIER_HOME" ]]
  then
    echo mkdir -p "$DOTHIER_HOME"
  fi

  if [[ "$DOTHIER_RECURSIVE" == true ]]
  then
    shopt -s globstar
    shopt -s dotglob

    local _FILE

    # root
    if [[ -d "${DOTHIER_DOTROOT}/.git" ]]
    then
      _URL="$( git -C "$DOTHIER_DOTROOT" remote get-url origin )"
      __dothier_git "$_URL" "$DOTHIER_DOTROOT" "$DH_DMODE"
    fi

    # hier
    for _FILE in "${DOTHIER_DOTROOT}"/**/*
    do
      if [[ "${_FILE##*/}" =~ ^${DOTHIER_FILE}$ ]]
      then
        __dothier_read "$_FILE"
      fi
    done
    unset _FILE

    shopt -u globstar
    shopt -u dotglob

    return
  else
    __dothier_read
  fi

} #__dothier

__dothier "$@"
